name: label-check

on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  label-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check added labels
        if: ${{ contains(github.event.pull_request.labels.*.name, 'major') == false && contains(github.event.pull_request.labels.*.name, 'minor') == false && contains(github.event.pull_request.labels.*.name, 'patch') == false && contains(github.event.pull_request.labels.*.name, 'skip-changelog') == false }}
        run: |
          echo "No valid labels found on this PR. Please add one of the following labels: major, minor, patch, skip-changelog"
          exit 1
