name: label-check

on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  label-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - if: ${{ contains(fromJson('["major", "minor", "patch", "skip-changelog"]'), github.event.label.name) == true }}
        run: exit 0
