name: release

on:
  release:
    types: [published]

defaults:
  run:
    shell: bash -l {0}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies from npm
        run: npm ci

      - name: Build Foundations
        run: npm run build
      
      - name: Confirm the build hasn't changed any files
        run: ./check-pristine-state package-lock.json

      - name: Release Foundations
        if: ${{ github.event_name == 'release' }}
        run: |
          git config --local user.email "200633985+skyscanner-backpack-bot[bot]@users.noreply.github.com"
          git config --local user.name "ollies-test-bot[bot]"
          npm run lerna:version -- $RELEASE_VERSION --no-push --yes
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
      
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Release Foundations
        if: ${{ github.event_name == 'release' }}
        run: |
          git config --local user.email "200633985+skyscanner-backpack-bot[bot]@users.noreply.github.com"
          git config --local user.name "ollies-test-bot[bot]"
          npm run lerna:publish -- bump from-git --yes --skip-git
          env: 
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            RELEASE_VERSION: ${{ github.event.release.tag_name }}